# AUTO-GENERATED by HyMeKo torch_dataflow backend.
# Do not edit. Regenerate via:
#   hymeko compile <source>.hymeko --format torch_dataflow --name <ClassName>
#
# Hierarchical-hypergraph projection π_dataflow(H): each layer
# hypervertex's body is stripped; only top-level layer / tensor /
# dataflow-hyperedge structure is emitted as a torch.nn.Module.

import torch
import torch.nn as nn

from ehk_torch_stub import HypergraphConv, GGKSpec


class {{config:robot_name}}(nn.Module):
    """Auto-generated from the hierarchical hypergraph dataflow projection."""

    def __init__(self):
        super().__init__()
{{#each layers}}{{#if field:d_in}}
        self.{{name}} = HypergraphConv(
            d_in={{field:d_in}},
            d_out={{field:d_out}},
            ggk_spec=GGKSpec(
{{#inherits kernel "bspline"}}                basis="bspline",
                degree={{field:kernel.degree}},
                n_knots={{field:kernel.n_knots}},
{{/inherits}}{{#inherits kernel "rbf"}}                basis="rbf",
                n_centres={{field:kernel.n_centres}},
{{/inherits}}{{#inherits kernel "bezier"}}                basis="bezier",
                degree={{field:kernel.degree}},
{{/inherits}}{{#inherits kernel "hermite"}}                basis="hermite",
                degree={{field:kernel.degree}},
{{/inherits}}{{#inherits kernel "wavelet"}}                basis="wavelet",
                n_knots={{field:kernel.n_knots}},
{{/inherits}}            ),
        )
{{/if}}{{/each}}

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        # Dataflow follows the order of @dataflow hyperedge declarations.
        # Each edge: (+ in_tensor, ~ layer, - out_tensor).
{{#each flows}}        {{bind:-:0}} = self.{{bind:~:0}}({{bind:+:0}})
{{/each}}{{#each outputs}}        return {{name}}
{{/each}}
