//! Arena `Ir` → SysML v2 textual model.
//!
//! Step 2b scope: walks the decl tree and emits
//!
//!   - a `package <Name> { … }` wrapper
//!   - metadata profile (`HyperedgeAnnotation`, `JointOrigin`)
//!   - one `part def <node>` per `ir.nodes[]` entry, with inline
//!     `attribute <child> :>> <value>;` lines for inline numeric / string
//!     / list values on direct children
//!   - one `connection def <edge>_arc_<i>` per hyperedge arc, carrying
//!     `@HyperedgeAnnotation { arity, sign, weight }`
//!   - a sibling `part <edge>_arc_<i>_arcs` with `:>> signs = (…)` and
//!     `:>> targets = (…)` so the n-ary sign vector survives the binary
//!     projection
//!
//! This matches the structural spine of the ground-truth
//! `docs/examples/hymeko_to_sysmlv2.md` render. Fully-faithful geometry /
//! material modelling is deferred — the emitter is scoped to preserve
//! topology + numeric scalars so the SysML model is structurally
//! equivalent to the `.hymeko` source.

use std::fmt::Write;

use hymeko::common::ids::DeclId;
use hymeko::ir::ir::{ArcRec, DeclKind, Ir, SignedRefR, ValueR};
use hymeko::resolution::interner::Interner;

fn decl_name<'a>(ir: &'a Ir, it: &'a Interner, did: DeclId) -> &'a str {
    it.resolve(ir.decl_nodes[did.0].name)
}

fn sign_value(r: &SignedRefR) -> &'static str {
    match r {
        SignedRefR::Plus(_) => "+1.0",
        SignedRefR::Minus(_) => "-1.0",
        SignedRefR::Neutral(_) => "0.0",
    }
}

fn format_num(n: f64) -> String {
    if n.fract() == 0.0 && n.abs() < 1e16 {
        format!("{:.1}", n)
    } else {
        format!("{}", n)
    }
}

fn sysml_literal(ir: &Ir, it: &Interner, v: &ValueR) -> String {
    match v {
        ValueR::Num(n) => format_num(*n),
        ValueR::Str(sid) => format!("\"{}\"", it.resolve(*sid)),
        ValueR::List(xs) => {
            let items: Vec<String> = xs.iter().map(|x| sysml_literal(ir, it, x)).collect();
            format!("({})", items.join(", "))
        }
        ValueR::Ref(did) => format!("\"{}\"", decl_name(ir, it, *did)),
    }
}

/// Emit `attribute <child_name> :>> <value>;` for every direct child of
/// `did` that carries a scalar/list value.
fn emit_node_attributes(ir: &Ir, it: &Interner, did: DeclId, depth: usize, out: &mut String) {
    let pad = "    ".repeat(depth);
    for child in ir.children(did) {
        if ir.decl_nodes[child.0].kind == DeclKind::HyperArc {
            continue;
        }
        let anno = &ir.decl_nodes[child.0].anno;
        if let Some(v) = &anno.value {
            let child_name = decl_name(ir, it, child);
            let _ = writeln!(
                out,
                "{pad}attribute {child_name} :>> {};",
                sysml_literal(ir, it, v)
            );
        }
    }
}

/// Emit a SysML v2 document. `package_name` is wrapped verbatim.
pub fn emit_sysml(ir: &Ir, interner: &Interner, package_name: &str) -> String {
    let mut out = String::new();
    emit_header(package_name, &mut out);
    emit_metadata_defs(&mut out);
    emit_part_defs(ir, interner, &mut out);
    emit_connection_defs(ir, interner, &mut out);
    let _ = writeln!(&mut out, "}}");
    out
}

fn emit_header(package_name: &str, out: &mut String) {
    let _ = writeln!(out, "// Generated by hymeko_emitter::emit_sysml (Plan 06, Step 2b)");
    let _ = writeln!(out, "// See docs/examples/hymeko_to_sysmlv2.md for the full output contract.");
    let _ = writeln!(out);
    let _ = writeln!(out, "package {package_name} {{");
    let _ = writeln!(out);
}

/// Metadata profile — matches the ground-truth doc.
fn emit_metadata_defs(out: &mut String) {
    let _ = writeln!(out, "    metadata def HyperedgeAnnotation {{");
    let _ = writeln!(out, "        attribute arity : ScalarValues::Integer;");
    let _ = writeln!(out, "        attribute sign : ScalarValues::Real;");
    let _ = writeln!(out, "        attribute weight : ScalarValues::Real;");
    let _ = writeln!(out, "    }}");
    let _ = writeln!(out);
    let _ = writeln!(out, "    metadata def JointOrigin {{");
    let _ = writeln!(out, "        attribute xyz : ScalarValues::Real[3];");
    let _ = writeln!(out, "        attribute rpy : ScalarValues::Real[3];");
    let _ = writeln!(out, "    }}");
    let _ = writeln!(out);
}

/// One `part def` per `NodeRec` in insertion order, carrying inline
/// scalar / list attributes for direct children.
fn emit_part_defs(ir: &Ir, interner: &Interner, out: &mut String) {
    for node in &ir.nodes {
        let name = decl_name(ir, interner, node.decl);
        let _ = writeln!(out, "    part def {name} {{");
        if !node.bases.is_empty() {
            let bases: Vec<&str> = node.bases.iter()
                .map(|b| decl_name(ir, interner, b.target()))
                .collect();
            let _ = writeln!(out, "        // specializes: {}", bases.join(", "));
        }
        emit_node_attributes(ir, interner, node.decl, 2, out);
        let _ = writeln!(out, "    }}");
    }
    let _ = writeln!(out);
}

/// One `connection def` + `part … _arcs` pair per hyperedge arc.
fn emit_connection_defs(ir: &Ir, interner: &Interner, out: &mut String) {
    for edge in &ir.edges {
        let name = decl_name(ir, interner, edge.decl);
        for (arc_idx, &arc_id) in edge.arcs.iter().enumerate() {
            let arc = &ir.arcs[arc_id.0];
            emit_arc(name, arc_idx, arc, ir, interner, out);
        }
    }
}

fn emit_arc(
    edge_name: &str,
    arc_idx: usize,
    arc: &ArcRec,
    ir: &Ir,
    interner: &Interner,
    out: &mut String,
) {
    let arity = arc.refs.len();
    let signs: Vec<&str> = arc.refs.iter().map(sign_value).collect();
    let targets: Vec<String> = arc.refs.iter()
        .map(|r| format!("\"{}\"", decl_name(ir, interner, r.target())))
        .collect();

    let _ = writeln!(out, "    connection def {edge_name}_arc_{arc_idx} {{");
    let _ = writeln!(
        out,
        "        @HyperedgeAnnotation {{ arity = {arity}; sign = {}; weight = 1.0; }}",
        signs.first().unwrap_or(&"0.0")
    );
    let _ = writeln!(out, "    }}");

    let _ = writeln!(out, "    part {edge_name}_arc_{arc_idx}_arcs {{");
    let _ = writeln!(out, "        attribute signs : ScalarValues::Real[*];");
    let _ = writeln!(out, "        attribute targets : ScalarValues::String[*];");
    let _ = writeln!(out, "        :>> signs   = ({});", signs.join(", "));
    let _ = writeln!(out, "        :>> targets = ({});", targets.join(", "));
    let _ = writeln!(out, "    }}");
}
