//! Arena `Ir` → Lean 4 proof-obligation skeletons.
//!
//! Step 2 scope: one trivially-provable `theorem` per node declaration,
//! intended as a scaffold for the formal-verification track. Later slices
//! can replace `by trivial` with actual invariants (e.g. level-monotonic
//! containment for G-SPHF).

use hymeko::ir::ir::Ir;
use hymeko::resolution::interner::Interner;

pub fn emit_lean4(ir: &Ir, interner: &Interner) -> String {
    let mut out = String::new();
    out.push_str("-- Generated by hymeko_emitter::emit_lean4 (Plan 06, Step 2a)\n\n");
    out.push_str("import Mathlib\n\n");
    for node in &ir.nodes {
        let name = interner.resolve(ir.decl_nodes[node.decl.0].name);
        let lower = name.to_lowercase();
        if lower.is_empty() {
            continue;
        }
        out.push_str(&format!("-- Obligation: {name} level invariant\n"));
        out.push_str(&format!(
            "theorem {lower}_level_invariant : True := by\n  trivial\n\n"
        ));
    }
    out
}
