//! Arena `Ir` → Rust trait skeletons.
//!
//! Step 2 scope: one `pub trait <PascalCased>` per node declaration,
//! with a single `fn process()` signature. Placeholder for richer
//! codegen (fields derived from `@anno` values, default impls for
//! geometry-shaped nodes, etc.) in later slices.

use hymeko::ir::ir::Ir;
use hymeko::resolution::interner::Interner;

fn to_pascal_case(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut upper_next = true;
    for c in s.chars() {
        if c == '_' || c == '-' || c == '.' {
            upper_next = true;
            continue;
        }
        if upper_next {
            out.extend(c.to_uppercase());
            upper_next = false;
        } else {
            out.push(c);
        }
    }
    out
}

pub fn emit_rust_stubs(ir: &Ir, interner: &Interner) -> String {
    let mut out = String::new();
    out.push_str("// Generated by hymeko_emitter::emit_rust_stubs (Plan 06, Step 2a)\n\n");

    for node in &ir.nodes {
        let name = interner.resolve(ir.decl_nodes[node.decl.0].name);
        let trait_name = to_pascal_case(name);
        if trait_name.is_empty() {
            continue;
        }
        out.push_str(&format!("pub trait {trait_name} {{\n"));
        out.push_str("    fn process(&self) -> Result<(), Box<dyn std::error::Error>>;\n");
        out.push_str("}\n\n");
    }
    out
}
