"""Read the policy's equivariance from the HyMeKo-generated structure, not from hand-coded flips.

The left-right reflection we hand-derived for the mirror-equivariant crab (Phase B) is, exactly, an
**automorphism of the HyMeKo-generated signed kinematic hypergraph**: the vertex permutation that swaps
``*_l/*_r``, ``*_fl/*_fr``, ``*_bl/*_br`` labels (midline parts map to themselves) and **preserves every
signed incidence**. So the symmetry group of the policy is *generated by the control language*, read off
the structure and **verified** — no guessed feature flips, no per-obs-representation re-derivation. This
is the concrete form of "use the HyMeKo structure as the learning signal": the structure supplies the
equivariance prior, and its induced action on the actuator (abduction) vertices gives the action-space
group action for free.

Design by contract: :func:`structural_reflection` VERIFIES the derived permutation is a genuine signed
automorphism and raises if the structure is not left-right symmetric — a violated postcondition is a bug
in the *structure* (or the label convention), surfaced early rather than as a silent wrong mirror.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Sequence

import numpy as np

# ordered so the longest side-token matches first (``_bl`` before ``_l``)
_SIDE_TOKENS: tuple[tuple[str, str], ...] = (("_fl", "_fr"), ("_bl", "_br"), ("_l", "_r"))


def mirror_label(label: str) -> str:
    """The left-right mirror of a HyMeKo vertex label (``hip_bracket_fl`` -> ``hip_bracket_fr``); a
    midline label (no side token) maps to itself. Involution: ``mirror_label(mirror_label(x)) == x``."""
    for a, b in _SIDE_TOKENS:
        if label.endswith(a):
            return label[: -len(a)] + b
        if label.endswith(b):
            return label[: -len(b)] + a
    return label


@dataclass(frozen=True)
class StructuralReflection:
    """The verified left-right reflection automorphism ``sigma`` of a signed hypergraph.

    # Invariants ``vertex_perm`` is an involution and an exact signed-incidence automorphism (both are
    checked at construction by :func:`structural_reflection`).
    """

    vertex_perm: np.ndarray                 # sigma: (n,) int, involution
    fixed: tuple[str, ...]                   # midline (self-mapped) labels
    swapped_pairs: tuple[tuple[str, str], ...]

    def action_perm(self, action_vertices: Sequence[int]) -> np.ndarray:
        """The permutation ``sigma`` induces on an ordered list of ACTUATOR vertices (e.g. the abduction
        joints) — the action-space relabelling for the equivariant policy.

        # Preconditions ``action_vertices`` is closed under ``sigma`` (each maps to another in the list).
        # Postconditions returns ``(len,)`` int slot-permutation; e.g. ``[fl,fr,bl,br] -> [1,0,3,2]``.
        """
        pos = {int(v): i for i, v in enumerate(action_vertices)}
        out = []
        for v in action_vertices:
            mv = int(self.vertex_perm[int(v)])
            if mv not in pos:
                raise ValueError(f"action vertex {v} maps under sigma to {mv}, not in the action set")
            out.append(pos[mv])
        return np.asarray(out, dtype=np.int64)


def structural_reflection(hg: object) -> StructuralReflection:
    """Derive + VERIFY the left-right reflection automorphism of a HyMeKo signed hypergraph.

    # Preconditions ``hg`` exposes ``vertex_labels`` (unique), ``edges`` ``(E,2)`` and ``signs`` ``(E,)``.
    # Postconditions the returned ``vertex_perm`` is an involution AND an exact signed automorphism.
    # Errors ``ValueError`` if labels are not left-right closed, or the permutation is not a signed
    automorphism (the structure is not left-right symmetric under the label convention).
    """
    labels = list(hg.vertex_labels)                          # type: ignore[attr-defined]
    idx = {lab: i for i, lab in enumerate(labels)}
    if len(idx) != len(labels):
        raise ValueError("vertex_labels must be unique to derive a reflection")
    perm = np.empty(len(labels), dtype=np.int64)
    for i, lab in enumerate(labels):
        m = mirror_label(lab)
        if m not in idx:
            raise ValueError(f"label {lab!r} mirrors to {m!r}, absent from the structure (not L-R closed)")
        perm[i] = idx[m]
    if not np.array_equal(perm[perm], np.arange(len(labels))):
        raise ValueError("label-derived reflection is not an involution")

    edges = np.asarray(hg.edges)                             # type: ignore[attr-defined]
    signs = np.asarray(hg.signs)                             # type: ignore[attr-defined]
    edge_sign = {(int(u), int(v)): int(s) for (u, v), s in zip(edges, signs)}
    for (u, v), s in edge_sign.items():
        if edge_sign.get((int(perm[u]), int(perm[v]))) != s:
            raise ValueError("label-derived reflection is NOT a signed-incidence automorphism "
                             f"(edge ({u},{v}) sign {s} not preserved) — structure not L-R symmetric")

    fixed = tuple(labels[i] for i in range(len(labels)) if perm[i] == i)
    swapped = tuple((labels[i], labels[perm[i]]) for i in range(len(labels)) if perm[i] > i)
    return StructuralReflection(vertex_perm=perm, fixed=fixed, swapped_pairs=swapped)
