"""Generate docs/editor/views/projects_data.js from the real .hymeko project files.

A *project* is a multi-file HyMeKo description the browser editor loads as a unit: the editable
instance files (robot / env / reward / strategy) plus the meta vocabulary they ``@"…"``-import,
which the editor places in its compile ``space``. Hand-embedding would drift as the files change, so
this reads the canonical files and emits the JS data module. Re-run after editing any project file.

    uv run python scripts/gen_editor_projects.py
"""
from __future__ import annotations

import re
from pathlib import Path

_ROBOTICS = Path("data/robotics")
_OUT = Path("docs/editor/views/projects_data.js")
_IMPORT = re.compile(r'@"([^"]+)"')

# (project id, label, [(instance file, label, view)]). Files resolve under data/robotics/.
_PROJECTS = [
    ("galambos", "Galambos MDP (RL grasp)", [
        ("galambos_planar.hymeko", "robot (two-arm hypergraph)", "hyper3d"),
        ("galambos_env.hymeko", "environment (zone / disk / workspace)", None),
        ("galambos_task.hymeko", "reward (declarative terms)", None),
        ("galambos_strategy.hymeko", "strategy (explore / exploit)", None),
    ]),
]


def _esc(src: str) -> str:
    """Escape a source string for a JS backtick template literal."""
    return src.replace("\\", "\\\\").replace("`", "\\`").replace("${", "\\${")


def _imports(src: str) -> list[str]:
    return list(dict.fromkeys(_IMPORT.findall(src)))   # order-preserving unique


def build() -> str:
    blocks = []
    for pid, label, files in _PROJECTS:
        meta: dict[str, str] = {}
        file_entries = []
        for fname, flabel, view in files:
            src = (_ROBOTICS / fname).read_text(encoding="utf-8")
            imps = _imports(src)
            for imp in imps:
                if imp not in meta:
                    meta[imp] = (_ROBOTICS / imp).read_text(encoding="utf-8")
            view_js = "null" if view is None else f'"{view}"'
            file_entries.append(
                f'    {{ name: "{fname}", label: {flabel!r}, imports: {imps!r}, '
                f'view: {view_js},\n      source: `{_esc(src)}` }},')
        meta_entries = [f'    "{k}": `{_esc(v)}`,' for k, v in meta.items()]
        blocks.append(
            f'  {{\n    id: "{pid}",\n    label: {label!r},\n'
            '    files: [\n' + "\n".join(file_entries) + "\n    ],\n"
            '    meta: {\n' + "\n".join(meta_entries) + "\n    },\n  },")
    return ("// GENERATED by scripts/gen_editor_projects.py — DO NOT EDIT BY HAND.\n"
            "// Re-run `uv run python scripts/gen_editor_projects.py` after changing a project file.\n"
            "// Each project: editable instance files + the meta vocab they @\"…\"-import (the\n"
            "// editor's compile space). Sources embedded because the browser cannot fetch data/.\n\n"
            "export const PROJECTS = [\n" + "\n".join(blocks) + "\n];\n")


def main() -> int:
    _OUT.parent.mkdir(parents=True, exist_ok=True)
    _OUT.write_text(build(), encoding="utf-8")
    print(f"wrote {_OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
