"""Generate HyMeKo descriptions for deep highway and ResMLP networks.

Writes .hymeko files of the form mirroring `data/nn/mnist_resmlp_3.hymeko`,
parameterised by depth and block kind. Each emitted .hymeko file
compiles via:

    hymeko compile <file.hymeko> --format torch_dataflow \
                   --name <ClassName> -o <emitted.py>

and the resulting class is a drop-in PyTorch nn.Module backed by
`ehk_torch_stub.{ResidualBlock|HighwayBlock}`.

Generates:
    data/nn/mnist_highway_{3,10,20}.hymeko
    data/nn/mnist_resmlp_{10,20,40}.hymeko

Run: python3 scripts/generate_deep_nn_hymeko.py
"""
from __future__ import annotations
from pathlib import Path

OUT_DIR = Path("data/nn")
OUT_DIR.mkdir(parents=True, exist_ok=True)


def generate(name: str, block_kind: str, n_blocks: int, hidden: int = 16,
             d_in: int = 784, d_out: int = 10) -> str:
    """Return the .hymeko source text for an MLP with `n_blocks` blocks of
    type `block_kind` (residual_block or highway_block) at hidden width
    `hidden`, mapping `d_in` → `hidden` → ... → `d_out`."""
    block_type_short = "ResMLP" if block_kind == "residual_block" else "HighwayMLP"
    head = f"""// Generated by scripts/generate_deep_nn_hymeko.py.
// {block_type_short}-{n_blocks} for MNIST: {d_in} → {hidden} [proj]
//   → {block_type_short}Block × {n_blocks} → {d_out} [head].
// Equivalent to the `{block_type_short}(hidden={hidden}, n_blocks={n_blocks})`
// PyTorch class in python/benches/thesis_iv_hard/run_benchmark.py.
//
// Compile:
//   hymeko compile data/nn/{name}.hymeko --format torch_dataflow \\
//       --name {block_type_short}{n_blocks}FromHymeko \\
//       -o /tmp/{name}_emitted.py

{name}_description {{
    @"meta_nn.hymeko";
    using nn.layers as lyr;
    using nn.tensors as ten;
}}

{name}: lyr, ten {{

    // Input / output tensors.
    x:  ten.t_input      {{ shape [{d_in}]; }}
    z0: ten.t_activation {{ shape [{hidden}]; }}
"""
    # Activation tensors after each block
    z_decls = "".join(
        f"    z{i + 1}: ten.t_activation {{ shape [{hidden}]; }}\n"
        for i in range(n_blocks)
    )
    y_decl = f"    y:  ten.t_output     {{ shape [{d_out}]; }}\n\n"

    # Initial projection
    proj_decl = f"    proj: lyr.linear_layer {{ d_in {d_in}; d_out {hidden}; }}\n\n"

    # Block decls
    block_decls = "".join(
        f"    block_{i + 1}: lyr.{block_kind} {{ hidden {hidden}; }}\n"
        for i in range(n_blocks)
    )
    block_decls += "\n"

    # Head
    head_decl = f"    head: lyr.linear_layer {{ d_in {hidden}; d_out {d_out}; }}\n\n"

    # Dataflow chain
    flow = "    @flow_proj:    lyr.dataflow { (+ x,  ~ proj,    - z0); }\n"
    for i in range(n_blocks):
        flow += (
            f"    @flow_block_{i + 1:02d}: lyr.dataflow "
            f"{{ (+ z{i}, ~ block_{i + 1}, - z{i + 1}); }}\n"
        )
    flow += f"    @flow_head:    lyr.dataflow {{ (+ z{n_blocks}, ~ head,    - y);  }}\n"
    flow += "}\n"

    return head + z_decls + y_decl + proj_decl + block_decls + head_decl + flow


def main() -> None:
    targets = [
        # name,                block_kind,        n_blocks
        ("mnist_highway_3",    "highway_block",   3),
        ("mnist_highway_10",   "highway_block",   10),
        ("mnist_highway_20",   "highway_block",   20),
        ("mnist_resmlp_10",    "residual_block",  10),
        ("mnist_resmlp_20",    "residual_block",  20),
        ("mnist_resmlp_40",    "residual_block",  40),
    ]
    for name, kind, n in targets:
        path = OUT_DIR / f"{name}.hymeko"
        path.write_text(generate(name, kind, n))
        size = path.stat().st_size
        print(f"  wrote {path}  ({size} bytes, {n} blocks of {kind})")


if __name__ == "__main__":
    main()
