"""Generate `ros_gz_bridge` YAML config from a HyMeKo coalition.

The Stage G demo uses `ros_gz_bridge` to translate between GZ
topics and ROS 2 topics. Instead of maintaining a hand-edited
YAML, we generate it from the same `triad_hri.hymeko` file that
declares the coalition + thresholds.

CLI:
    python -m signedkan_wip.src.rapport_ros2.bridge_config \\
        data/coalitions/triad_hri.hymeko \\
        > bridge.yaml

Plan: docs/plans/2026-05-18-gz-rapport-demo/.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

from ..rapport.coalition import Coalition, GzBinding, load_coalition


def render_bridge_yaml(coalition: Coalition) -> str:
    """Render a `ros_gz_bridge` parameter-bridge YAML for the
    coalition's GZ bindings.

    GZ→ROS direction for pose topics (geometry_msgs/Pose);
    ROS→GZ direction for cmd_vel topics (geometry_msgs/Twist) +
    gaze_cmd topics (geometry_msgs/Point).
    """
    out: list[str] = [
        "# Auto-generated by signedkan_wip.src.rapport_ros2.bridge_config",
        f"# Source: {coalition.name}",
        "",
    ]
    for agent_name, binding in sorted(coalition.gz_bindings.items()):
        out.append(f"# ─── {agent_name} ────────────────────────────")
        # Pose topic — GZ → ROS
        out.append(f"- ros_topic_name: \"{binding.pose_topic}\"")
        out.append(f"  gz_topic_name: \"{binding.pose_topic}\"")
        out.append("  ros_type_name: \"geometry_msgs/msg/Pose\"")
        out.append("  gz_type_name: \"gz.msgs.Pose\"")
        out.append("  direction: GZ_TO_ROS")
        out.append("")
        if binding.cmd_vel_topic:
            out.append(f"- ros_topic_name: \"{binding.cmd_vel_topic}\"")
            out.append(f"  gz_topic_name: \"{binding.cmd_vel_topic}\"")
            out.append("  ros_type_name: \"geometry_msgs/msg/Twist\"")
            out.append("  gz_type_name: \"gz.msgs.Twist\"")
            out.append("  direction: ROS_TO_GZ")
            out.append("")
        if binding.camera_topic:
            out.append(f"- ros_topic_name: \"{binding.camera_topic}\"")
            out.append(f"  gz_topic_name: \"{binding.camera_topic}\"")
            out.append("  ros_type_name: \"sensor_msgs/msg/Image\"")
            out.append("  gz_type_name: \"gz.msgs.Image\"")
            out.append("  direction: GZ_TO_ROS")
            out.append("")
    return "\n".join(out) + "\n"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("coalition", type=str,
                    help="Path to a .hymeko coalition spec.")
    ap.add_argument("-o", "--output", default="-",
                    help="Output path (default: stdout).")
    args = ap.parse_args()
    coalition = load_coalition(args.coalition)
    yaml_text = render_bridge_yaml(coalition)
    if args.output == "-":
        sys.stdout.write(yaml_text)
    else:
        Path(args.output).write_text(yaml_text)


if __name__ == "__main__":
    main()
